"""empty message

Revision ID: 12cbe5c35cec
Revises: 19e28e1e2ce8
Create Date: 2015-01-08 17:21:28.225067

"""

# revision identifiers, used by Alembic.
revision = '12cbe5c35cec'
down_revision = '19e28e1e2ce8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawl', sa.Column('status', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crawl', 'status')
    ### end Alembic commands ###
